### ISSUE TITLE
required API token

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [ThinkR-open/rtodoist#8]
Hello,

I installed your package to see what it looks like since there were no images in your README file or github page. 
After i used the starter code I see that I require a API token, **it would have been nice to know this before I installed your package**. 

 Maybe you assumed that everyone knows that you need this specific API key token to make this work but that is incorrect. 
 
 Could you add what your working demo code looks like and tell people you REQUIRE a API key just in case the next person doesn't have to waste their time.

**Comment by statnmap** [comment]
It is true that we could have been nice to make it clearer in the README. 
However, if you follow the first link of the said README, you can see that todoist speaks about the required token: https://developer.todoist.com/sync/v8/#getting-started
Also, if you read the vignette of the package, in the website linked on the frontpage of the GitHub project, you can read it too: https://thinkr-open.github.io/rtodoist/articles/how_it_works.html

Note that for any tool that deals with API, a token or credential is generally required.

We are open to a pull request on the README if you would like to propose a better way to say it.
Thank you

**Comment by VincentGuyader** [comment]
hi @PythonCoderUnicorn ,

you didn't answer to the response @statnmap made to you.
is everything ok ? can I close this issue ?

Regards
